version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 4000:8080
    depends_on:
      - db
    env_file: .env
    restart: always


  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5435:5432
    env_file: .env
    volumes:
      - greenlight_db:/var/lib/postgresql/data
    restart: always

volumes:
  greenlight_db:
